enroll-me:
  PyCon CZ:
    users:
    - ahlinc
    - amsoell
    - asottile
    - backslash7
    - bluebirrrrd
    - chr0139
    - edasubert
    - encukou
    - frenzymadness
    - Glutexo
    - Iref
    - isaranova
    - Ivuska
    - jackiekazil
    - JakubDotPy
    - Kani999
    - LorenaLorene
    - martinrakovec
    - martinrakovec
    - matrixise
    - messa
    - michalpazdera
    - moisesguimaraes
    - mpavlase
    - paynes
    - sn0wrainy
    - the-cat
    - TomasTomecek
    - torsava
    - tulphoon
    - vklikar
    - webknjaz
    - zhukovgreen
    - 6w3
